# Configuration for 04_video_renderer service

# Input/Output settings
io:
  input: "data/storyboard_with_images.json"  # From service 03.5
  output_dir: "out/clips"
  audio_file: "data/generated_song.mp3"  # From service 01
  ref_image: null  # Not used - images come from storyboard
  
# Video generation server
video_server:
  url: "http://localhost:8004"
  timeout: 300  # 5 minutes for video generation
  num_inference_steps: 25
  guidance_scale: 7.5
  negative_prompt: null  # Optional negative prompt

# Video generation engine (used by video server)
engine:
  type: "Wan2.2"  # Options: "Wan2.2", "AnimateDiff", "SkyReelsV1", "M4V"
  
  # Wan2.2-S2V-14B settings (primary)
  wan2:
    model: "Wan-AI/Wan2.2-S2V-14B"
    num_inference_steps: 25
    guidance_scale: 7.5
  
  # AnimateDiff-SDXL settings (fallback)
  animatediff:
    model: "guoyww/animatediff-sdxl"
    pipeline_class: "AnimateDiffPipeline"
    num_inference_steps: 25
    guidance_scale: 7.5
    
  # Alternative engines (placeholder)
  skyreels:
    model: "skyreels/skyreels-v1"
    num_inference_steps: 20
    guidance_scale: 8.0
    
  m4v:
    model: "m4v/m4v-v1"
    num_inference_steps: 30
    guidance_scale: 7.0

# Video settings
video:
  fps: 12
  resolution: [512, 512]
  format: "mp4"
  codec: "h264"
  bitrate: "2M"
  
# Generation parameters
generation:
  batch_size: 1
  num_frames: null  # Auto-calculate based on duration
  motion_bucket_id: 127
  fps_id: 6
  
# Consistency settings
consistency:
  use_seed: true
  use_ref_image: true
  seed_offset: 0
  
# LoRA support (optional)
lora:
  enabled: false
  path: "lora/"
  weight: 0.8
  
# Performance settings (for video server)
performance:
  device: "auto"  # Options: "auto", "cpu", "cuda", "mps"
  memory_efficient: true
  compile: false  # torch.compile() for speed 